Repository archecrawl/archecrawl, pull requests merged in 2023-05, with the labels that each got.

#10 3 AM gaming UI
  Content.Client/Administration/UI/BanList/BanListControl.xaml
  Content.Client/Administration/UI/BanList/BanListIdsPopup.xaml
  Content.Client/Administration/UI/Bwoink/BwoinkControl.xaml
  Content.Client/Administration/UI/CustomControls/HSeparator.cs
  Content.Client/Administration/UI/CustomControls/PlayerListControl.xaml.cs
  Content.Client/Administration/UI/CustomControls/VSeparator.cs
  Content.Client/Administration/UI/Logs/AdminLogsControl.xaml
  Content.Client/Administration/UI/Notes/AdminNotesControl.xaml
  Content.Client/Administration/UI/Notes/AdminNotesLinePopup.xaml
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTab.xaml.cs
  Content.Client/Cargo/UI/CargoProductRow.xaml
  Content.Client/PDA/PDANavigationButton.xaml.cs
  Content.Client/PDA/PDAProgramItem.xaml.cs
  Content.Client/PDA/PDASettingsButton.xaml.cs
  Content.Client/ParticleAccelerator/UI/ParticleAcceleratorControlMenu.cs
  Content.Client/Preferences/UI/CharacterSetupGui.xaml.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Content.Client/Stylesheets/StyleBase.cs
  Content.Client/Stylesheets/StyleNano.cs
  Content.Client/Stylesheets/StyleSpace.cs
  Content.Client/UserInterface/Controls/MenuButton.cs
  Content.Client/UserInterface/Screens/SeparatedChatGameScreen.xaml
  Content.Client/UserInterface/Systems/Atmos/GasTank/GasTankWindow.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterButton.cs
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml
  Content.Client/Wires/UI/WiresMenu.cs
  Resources/Textures/Interface/Nano/chat_sub_background.png
  Resources/Textures/Interface/Nano/checkbox_checked.svg
  Resources/Textures/Interface/Nano/checkbox_checked.svg.96dpi.png
  Resources/Textures/Interface/Nano/checkbox_unchecked.svg
  Resources/Textures/Interface/Nano/checkbox_unchecked.svg.96dpi.png
  Resources/Textures/Interface/Nano/light_panel_background_bordered.png
  Resources/Textures/Interface/Nano/lineedit.png
  Resources/Textures/Interface/Nano/stripeback.svg
  Resources/Textures/Interface/Nano/stripeback.svg.96dpi.png
  Resources/Textures/Interface/Nano/tabcontainer_panel.png
  Resources/Textures/Interface/Nano/tooltip.png
  Resources/Textures/Interface/Nano/transparent_window_background_bordered.png
  Resources/Textures/Interface/Nano/whisper.png
  Resources/Textures/Interface/Nano/window_background.png
  Resources/Textures/Interface/Nano/window_background_bordered.png
  Resources/Textures/Interface/Nano/window_header.png
  Resources/Textures/Interface/Nano/window_header_alert.png
Labels: Changes: UI

#11 Basic Stats API
  Content.Client/CharacterInfo/CharacterInfoSystem.cs
  Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
  Content.Client/UserInterface/Systems/Character/Windows/CharacterWindow.xaml
  Content.Client/_ArcheCrawl/Stats/StatsSystem.cs
  Content.Server/_ArcheCrawl/Stats/StatsSystem.cs
  Content.Shared/_ArcheCrawl/Stats/Components/StatsComponent.cs
  Content.Shared/_ArcheCrawl/Stats/SharedStatsSystem.cs
  Content.Shared/_ArcheCrawl/Stats/StatPrototype.cs
  Resources/Locale/en-US/_ArcheCrawl/stats/stats.ftl
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/_ArcheCrawl/Stats/stats.yml
Labels: Changes: UI

#12 Upstream merge tool + icon fix
  Resources/Textures/Logo/icon.ico
  Resources/Textures/Logo/icon/icon-128x128.png
  Resources/Textures/Logo/icon/icon-16x16.png
  Resources/Textures/Logo/icon/icon-24x24.png
  Resources/Textures/Logo/icon/icon-256x256.png
  Resources/Textures/Logo/icon/icon-32x32.png
  Resources/Textures/Logo/icon/icon-48x48.png
  Resources/Textures/Logo/icon/icon-64x64.png
  Tools/upstream_merge_tool.ps1
Labels: No C#

#14 Clothing
  Resources/Prototypes/_ArcheCrawl/Entities/Clothing/Shoes/shoes.yml
  Resources/Prototypes/_ArcheCrawl/Entities/Clothing/Uniforms/uniforms.yml
  Resources/Textures/_ArcheCrawl/Clothing/Shoes/adventurer_boots.rsi/equipped-FEET.png
  Resources/Textures/_ArcheCrawl/Clothing/Shoes/adventurer_boots.rsi/icon.png
  Resources/Textures/_ArcheCrawl/Clothing/Shoes/adventurer_boots.rsi/inhand-left.png
  Resources/Textures/_ArcheCrawl/Clothing/Shoes/adventurer_boots.rsi/inhand-right.png
  Resources/Textures/_ArcheCrawl/Clothing/Shoes/adventurer_boots.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/ranger_tunic.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/ranger_tunic.rsi/icon.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/ranger_tunic.rsi/inhand-left.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/ranger_tunic.rsi/inhand-right.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/ranger_tunic.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/thief_tunic.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/thief_tunic.rsi/icon.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/thief_tunic.rsi/inhand-left.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/thief_tunic.rsi/inhand-right.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/thief_tunic.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/warrior_coat.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/warrior_coat.rsi/icon.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/warrior_coat.rsi/inhand-left.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/warrior_coat.rsi/inhand-right.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/warrior_coat.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/wizard_garb.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/wizard_garb.rsi/icon.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/wizard_garb.rsi/inhand-left.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/wizard_garb.rsi/inhand-right.png
  Resources/Textures/_ArcheCrawl/Clothing/Uniforms/wizard_garb.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-blade-left.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-blade-right.png
Labels: No C#, Changes: Sprites

#15 Walls and Floors
  Resources/Locale/en-US/_ArcheCrawl/tiles/tiles.ftl
  Resources/Prototypes/_ArcheCrawl/Entities/Structures/Walls/base_wall.yml
  Resources/Prototypes/_ArcheCrawl/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/_ArcheCrawl/Tiles/dungeon.yml
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/full.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall0.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall1.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall2.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall3.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall4.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall5.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall6.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/dungeon_wall.rsi/wall7.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/rock.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/rock_east.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/rock_north.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/rock_south.png
  Resources/Textures/_ArcheCrawl/Structures/Walls/rock.rsi/rock_west.png
  Resources/Textures/_ArcheCrawl/Tiles/attributions.yml
  Resources/Textures/_ArcheCrawl/Tiles/stone_dungeon.png
Labels: No C#, Changes: Sprites

#18 Update the readme
  README.md
Labels: No C#

#19 Enchantments and flame enchantment
  Content.Client/_ArcheCrawl/Enchantments/EnchantmentSystem.cs
  Content.Server/_ArcheCrawl/Enchantments/EnchantmentSystem.cs
  Content.Shared/_ArcheCrawl/Enchantments/Components/EnchantableComponent.cs
  Content.Shared/_ArcheCrawl/Enchantments/Components/EnchantmentComponent.cs
  Content.Shared/_ArcheCrawl/Enchantments/Components/EnchantmentVisualsComponent.cs
  Content.Shared/_ArcheCrawl/Enchantments/SharedEnchantmentSystem.cs
  Resources/Locale/en-US/_ArcheCrawl/enchantments/enchantments.ftl
  Resources/Prototypes/_ArcheCrawl/Enchantments/enchantments.yml
  Resources/Prototypes/_ArcheCrawl/Entities/Objects/Weapons/Melee/ac_base_weapon.yml
  Resources/Prototypes/_ArcheCrawl/tags.yml
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-handle-left.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-handle-right.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword-inhand.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword-inhand.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword-inhand.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword.rsi/flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword.rsi/meta.json
Labels: Changes: Sprites

#22 Wall Torches
  Resources/Prototypes/_ArcheCrawl/Enchantments/enchantments.yml
  Resources/Prototypes/_ArcheCrawl/Entities/Structures/Lighting/lighting.yml
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword-inhand.rsi/inhand-left-flame.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword-inhand.rsi/inhand-right-flame.png
  Resources/Textures/_ArcheCrawl/Structures/Lighting/torches.rsi/fixture.png
  Resources/Textures/_ArcheCrawl/Structures/Lighting/torches.rsi/flame.png
  Resources/Textures/_ArcheCrawl/Structures/Lighting/torches.rsi/meta.json
Labels: No C#, Changes: Sprites

#24 door and tiles
  Resources/Prototypes/_ArcheCrawl/Entities/Structures/Doors/doors.yml
  Resources/Prototypes/_ArcheCrawl/Tiles/dungeon.yml
  Resources/Textures/_ArcheCrawl/Structures/Doors/wood_door.rsi/closed.png
  Resources/Textures/_ArcheCrawl/Structures/Doors/wood_door.rsi/closing.png
  Resources/Textures/_ArcheCrawl/Structures/Doors/wood_door.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Structures/Doors/wood_door.rsi/open.png
  Resources/Textures/_ArcheCrawl/Structures/Doors/wood_door.rsi/opening.png
  Resources/Textures/_ArcheCrawl/Tiles/attributions.yml
  Resources/Textures/_ArcheCrawl/Tiles/stone_dungeon2.png
  Resources/Textures/_ArcheCrawl/Tiles/stone_dungeon3.png
Labels: No C#, Changes: Sprites
