Repository archecrawl/archecrawl, pull requests merged in 2023-06, with the labels that each got.

#28 Basic dungeon
  Resources/Maps/_ArcheCrawl/Dungeon/stone_dungen.yml
  Resources/Prototypes/_ArcheCrawl/Procedural/Themes/stone.yml
  Resources/Prototypes/_ArcheCrawl/Procedural/dungeon_configs.yml
  Resources/Prototypes/_ArcheCrawl/tags.yml
Labels: No C#

#29 Random crits
  Content.Client/_ArcheCrawl/Enchantments/EnchantmentSystem.cs
  Content.Shared/Inventory/InventorySystem.Relay.cs
  Content.Shared/_ArcheCrawl/Crits/Components/BonusCritChanceComponent.cs
  Content.Shared/_ArcheCrawl/Crits/Components/BonusCritDamageComponent.cs
  Content.Shared/_ArcheCrawl/Crits/Components/RandomCritMeleeComponent.cs
  Content.Shared/_ArcheCrawl/Crits/RandomCritSystem.cs
  Content.Shared/_ArcheCrawl/Enchantments/Components/EnchantmentInhandVisualsComponent.cs
  Content.Shared/_ArcheCrawl/Enchantments/Components/EnchantmentVisualsComponent.cs
  Content.Shared/_ArcheCrawl/Enchantments/SharedEnchantmentSystem.cs
  Resources/Audio/_ArcheCrawl/attributions.yml
  Resources/Audio/_ArcheCrawl/crit.ogg
  Resources/Locale/en-US/_ArcheCrawl/crits/crits.ftl
  Resources/Locale/en-US/_ArcheCrawl/enchantments/enchantments.ftl
  Resources/Prototypes/_ArcheCrawl/Enchantments/enchantments.yml
  Resources/Prototypes/_ArcheCrawl/Entities/Objects/Weapons/Melee/ac_base_weapon.yml
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/lucky.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/club.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/lucky.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/dagger.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/lucky.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/spear.rsi/meta.json
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword.rsi/lucky.png
  Resources/Textures/_ArcheCrawl/Objects/Weapons/Melee/sword.rsi/meta.json
Labels: Changes: Sprites

#35 3 AM Gaming UI Pt. 2
  Content.Shared/Chat/ChatChannelExtensions.cs
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Textures/Interface/Actions/harm.png
  Resources/Textures/Interface/Actions/harmOff.png
  Resources/Textures/Interface/Default/SlotBackground.png
  Resources/Textures/Interface/Default/Slots/back.png
  Resources/Textures/Interface/Default/Slots/belt.png
  Resources/Textures/Interface/Default/Slots/ears.png
  Resources/Textures/Interface/Default/Slots/ears_headset.png
  Resources/Textures/Interface/Default/Slots/glasses.png
  Resources/Textures/Interface/Default/Slots/gloves.png
  Resources/Textures/Interface/Default/Slots/hand_l.png
  Resources/Textures/Interface/Default/Slots/hand_l_no_letter.png
  Resources/Textures/Interface/Default/Slots/hand_m.png
  Resources/Textures/Interface/Default/Slots/hand_r.png
  Resources/Textures/Interface/Default/Slots/hand_r_no_letter.png
  Resources/Textures/Interface/Default/Slots/head.png
  Resources/Textures/Interface/Default/Slots/id.png
  Resources/Textures/Interface/Default/Slots/inventory.png
  Resources/Textures/Interface/Default/Slots/mask.png
  Resources/Textures/Interface/Default/Slots/neck.png
  Resources/Textures/Interface/Default/Slots/pda.png
  Resources/Textures/Interface/Default/Slots/pocket.png
  Resources/Textures/Interface/Default/Slots/shoes.png
  Resources/Textures/Interface/Default/Slots/suit.png
  Resources/Textures/Interface/Default/Slots/suit_storage.png
  Resources/Textures/Interface/Default/Slots/uniform.png
  Resources/Textures/Interface/Default/Slots/web.png
  Resources/Textures/Interface/Default/blocked.png
  Resources/Textures/Interface/Default/left_arrow.svg.192dpi.png
  Resources/Textures/Interface/Default/right_arrow.svg.192dpi.png
  Resources/Textures/Interface/Default/slot_highlight.png
  Resources/Textures/Interface/Inventory/hand_active.png
  Resources/Textures/Interface/Inventory/hand_slot_highlight.png
  Resources/Textures/Interface/Inventory/inv_slot_background.png
  Resources/Textures/Interface/Misc/health_bar.rsi/icon.png
  Resources/Textures/Interface/Misc/progress_bar.rsi/icon.png
Labels: Changes: Sprites

#32 Stat effects! And a few basic examples.
  Content.Server/_ArcheCrawl/StatusEffects/EffectInflictorsSystem.cs
  Content.Server/_ArcheCrawl/StatusEffects/EffectsSystem.cs
  Content.Server/_ArcheCrawl/StatusEffects/StatEffectsSystem.cs
  Content.Shared/_ArcheCrawl/CCVar/CCVars.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Activations/ActivateEffectEveryUpdateComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Activations/ActivateEffectOnDamageComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Activations/ActivateEffectOnTimeoutComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Effects/Active/AdjustEffectStrengthEffectComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Effects/Active/DamageEntityEffectComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Effects/Inflictors/InflictEffectOnDamageComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Effects/Passive/AttackDamageEffectComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/Effects/Passive/DefenceEffectComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/StatEffectComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/Components/StatEffectsVictimComponent.cs
  Content.Shared/_ArcheCrawl/StatusEffects/EffectActivationsSystem.cs
  Content.Shared/_ArcheCrawl/StatusEffects/SharedEffectsSystem.cs
  Content.Shared/_ArcheCrawl/StatusEffects/SharedStatEffectsSystem.cs
  Content.Shared/_ArcheCrawl/StatusEffects/StatEffectEvents.cs
  Resources/Locale/en-US/_ArcheCrawl/stat-effects/stat-effects.ftl
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/_ArcheCrawl/Enchantments/enchantments.yml
  Resources/Prototypes/_ArcheCrawl/StatusEffects/damaging.yml
  Resources/Prototypes/_ArcheCrawl/StatusEffects/negative.yml
  Resources/Prototypes/_ArcheCrawl/StatusEffects/positive.yml
Labels: Status: Needs Review
